
spring:
    application:
      name: gateway-service
    cloud:
      gateway:
        routes:
          - id: users_router
            uri: http://localhost:8090/
            predicates:
              - Path=/**
          - id: logs_router
            uri: http://localhost:8091/
            predicates:
              - Path=/logs/**
server:
  port: 8181